name: Build
on: [push]
env:
  QT_VERSION: 5.15.0

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-16.04
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ env.QT_VERSION }}
    - uses: actions/checkout@v2
    - name: Compile
      run: cmake -B build && cmake --build build --parallel
      env:
        CC: gcc-9
        CXX: g++-9
